### ISSUE TITLE
can't install...

### ISSUE THREAD

**Issue by Zibri** [christian-bromann/devtools-backend#11]
```
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle devtools-backend@0.0.0~prestart: devtools-backend@0.0.0
6 info lifecycle devtools-backend@0.0.0~start: devtools-backend@0.0.0
7 verbose lifecycle devtools-backend@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle devtools-backend@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zibri/devtools-backend/node_modules/.bin:/home/zibri/go/bin/:/home/zibri/google-cloud-sdk/bin:/home/zibri/lgtv/toolchain/bin/:/usr/local/share/webOS_TV_SDK/CLI/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle devtools-backend@0.0.0~start: CWD: /home/zibri/devtools-backend
10 silly lifecycle devtools-backend@0.0.0~start: Args: [ '-c', 'npm run start:server' ]
11 silly lifecycle devtools-backend@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle devtools-backend@0.0.0~start: Failed to exec start script
13 verbose stack Error: devtools-backend@0.0.0 start: `npm run start:server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid devtools-backend@0.0.0
15 verbose cwd /home/zibri/devtools-backend
16 verbose Linux 4.13.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error devtools-backend@0.0.0 start: `npm run start:server`
22 error Exit status 1
23 error Failed at the devtools-backend@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by Zibri** [comment]
hmm probably I solved it doing:

yarn install --ignore-platform
then
yarn build
then 
yarn run start

and it worked...
but I wonder... why the error before?

**Comment by christian-bromann** [comment]
You need to install all dependencies and build the project before running any services.

**Comment by Zibri** [comment]
I did as written in the README from ubuntu 17.10
