### ISSUE TITLE
Missing readConfig() in utils.js

### ISSUE THREAD

**Issue by Efefefef** [christian-bromann/devtools-backend#4]
Apparently you got missing readConfig() function in utils.js module
It is being imported in lib/proxy.js then

So when you start the devtools-backend server and process html through it you got an error

`TypeError: (0 , _utils.readConfig) is not a function
    at Proxy.proxy (/Users/andreiklimenok/workspace/devtools-backend/build/proxy.js:133:58)
    at Layer.handle [as handle_request] (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/index.js:281:22
    at param (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/andreiklimenok/workspace/devtools-backend/node_modules/express/lib/router/index.js:275:10)`

**Comment by christian-bromann** [comment]
Fixed with latest update.
